Implemented Point, Shape and Triangle classes
nikitin-i/software-designs-and-algorithms pull request #1
Opened 2021-09-20 16:31 UTC by nikitin-i

2021-09-22 09:17 UTC, Hundd requested changes

2021-09-22 09:17 UTC, Hundd commented on src/Point.ts
> +    constructor(x?: number, y?: number) {
You can use default values
```suggestion
    constructor(x?: number = 0, y?: number = 0) {
```

2021-09-22 09:17 UTC, Hundd commented on src/Point.ts
> +            return Math.sqrt((newX['_x'] - this._x) ** 2 + (newX['_y'] - this._y) ** 2);
you can specify getter for `x` and `y` so that you don't rely on realization

2021-09-22 09:17 UTC, Hundd commented on src/Shape.ts
> +        const points: string = this.points.map(point => [`(${point['_x']}, ${point['_y']})`]).join(', ');
you can use toString method from Point class here

2021-09-22 09:17 UTC, Hundd commented on src/Shape.ts
> +        const sideFirst: number = Math.round(this.points[0].distance(this.points[1]['_x'], this.points[1]['_y']) * 10) / 10;
please use methods defined in Point class for accepting another point. 
```
this.point[0].distanance(this.point[1])
```

2021-09-22 09:17 UTC, Hundd commented on src/Shape.ts
> +        const sideSecond: number = Math.round(this.points[1].distance(this.points[2]['_x'], this.points[2]['_y']) * 10) / 10;
if types can be calculated in run type there is no need specify them every time
const sideSecond = ...

2021-09-22 09:17 UTC, Hundd commented on src/Shape.ts
> +        return sideFirst + sideSecond + sideThird;
Method should work with any number of Points

2021-09-22 09:17 UTC, Hundd commented on src/Triangle.ts
> +        const isScalene: string = (sideFirst !== sideSecond && sideFirst !== sideThird && sideSecond !== sideThird) && 'scalene triangle';
`is` prefix generally have Boolean variables

2021-09-22 09:17 UTC, Hundd commented on src/Triangle.ts
> +        const isScalene: string = (sideFirst !== sideSecond && sideFirst !== sideThird && sideSecond !== sideThird) && 'scalene triangle';
you can simplify this a bit by using `Set`
```js
const sizes = new Set([sideFirst, sideSecond, sideThird]).size
return [,'equilateral triangle', 'isosceles triangle', 'scalene triangle'][sizes]
```

2021-10-04 20:48 UTC, closed without merging

2021-10-04 20:48 UTC, nikitin-i commented
Closed